#!/bin/bash
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 1&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 2&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 3&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 4&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 5&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 6&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 7&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1 --RANDOM_SEED 8&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 9&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 10&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 11&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 12&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 13&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 14&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 15&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 16&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 17&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 18&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 19&
python al_hyper_search.py --dataset_path ../datasets/dwtc/aft.csv --CORES 1  --RANDOM_SEED 20
